version: '2'
services:
  fe.aodabong:
    container_name: fe.aodabong
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
